Output demo.gif

Require echo

Set Shell "bash"
Set Framerate 24
Set FontSize 32
Set Width 1200
Set Height 600

Type "dune exec --no-print-directory ./main.exe"
Enter
Sleep 1s
Down
Sleep 0.2s
Down
Sleep 0.2s
Down
Sleep 0.2s
Down
Sleep 0.2s
Down
Sleep 0.2s
Down
Sleep 0.2s
Space
Sleep 0.2s
Space
Sleep 0.2s
Down
Sleep 0.2s
Down
Sleep 0.3s
Up
Sleep 0.3s
Up
Sleep 0.3s
Up
Sleep 0.3s
Up
Sleep 0.3s
Up
Sleep 0.2s
Down
Sleep 0.2s
Down
Sleep 2s