val line : Sprite.t
val dot : Sprite.t
val mini_dot : Sprite.t
val jump : Sprite.t
val pulse : Sprite.t
val points : Sprite.t
val meter : Sprite.t
val globe : Sprite.t
val moon : Sprite.t
val monkey : Sprite.t
val hamburger : Sprite.t
val ellipsis : Sprite.t
